os: linux
dist: bionic
language: python
services:
  - docker
  - mysql
python:
  - 3.8
before_install:
  - mysql -e 'CREATE DATABASE testing CHARACTER SET utf8 COLLATE utf8_general_ci;'
script:
  - pytest -v
before_deploy:
  - if [ $TRAVIS_BRANCH == "master" ]; then export EB_ENV=notification-prd-apii; fi
  - if [ $TRAVIS_BRANCH == "develop" ]; then export EB_ENV=notification-dev-api; fi
  - export ARTIFACT_PRE=$(echo $TRAVIS_REPO_SLUG | sed "s_^.*/__")
  - export ARTIFACT_NAME=${ARTIFACT_PRE}-$(git describe|tr . _)-$(date +%y%m%d_%H%M%S)
  - export ELASTIC_BEANSTALK_LABEL=$ARTIFACT_NAME
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  region: ap-northeast-2
  bucket: elasticbeanstalk-ap-northeast-2-884465654078
  bucket_path: notification-api
  app: notification-api
  env: $EB_ENV
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
#notifications:
#  slack:
#    - rooms:
#      - secure: ***********
#      if: branch = master
#      template:
#        - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
#    - rooms:
#      - secure: ***********
#      if: branch = staging
#      template:
#        - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
#    - rooms:
#      - secure: ***********
#      if: branch = develop
#      template:
#        - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
